# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('A', 'Author'), ('J', 'Journal'), ('JS', 'Journal-Sub'), ('C', 'Conference'), ('CS', 'Conference-Sub')], max_length=2)),
                ('short', models.TextField()),
                ('name', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Page')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Page')),
                ('pub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Publication')),
            ],
        ),
    ]
